---
apiVersion: v1
kind: Pod
metadata:
  name: molecule
  labels:
    app: molecule

spec:
  serviceAccountName: molecule-kubevirt
  containers:
  - name: molecule
    image: quay.io/jseguillon/molecule_kubevirt_demo:latest
    imagePullPolicy: IfNotPresent
    command: [ "molecule", "test" ]
    env:
      - name: PY_COLORS
        value: '1'
      - name: ANSIBLE_FORCE_COLOR
        value: '1'
  restartPolicy: Never